### ISSUE TITLE
Bug after uploading file with file browser

### ISSUE THREAD

**Issue by pguedesbr** [f4bsch/WP-Filebase#10] opened 2015-11-18 18:03 UTC
In the admin, file browser page of wp-filebase, after you upload a file to a folder/category, it will show up in that folder/category, with 2 links (edit / remove).

When you click in remove, it will remove the parent category in which the file has just been uploaded to.
When you try to drag/move the file, it will move the whole parent category, ultimately causing an error if  you move it to a subcategory of it (cant move category into a subcategory of itself).

None of theses errors happen if you refresh the file browser page after uploading files.

**Comment by f4bsch** [comment] 2015-12-08 14:43
Couldnt reproduce it. Can you do screen capture (GIF or video)?

**Comment by pguedesbr** [comment] 2015-12-08 18:06
Hello

Here is a demo of the error when you drag a file to another folder right after uploading it:
https://www.youtube.com/watch?v=GggPsQuPfHk

Basically the error seems to be related to the event listeners, which is the same cause of the other case (clicking remove on a file removes its category/folder)

Hope that helps.

**Comment by f4bsch** [comment] 2015-12-08 22:42
Thanks, the video made it clear.

Fixed with https://github.com/f4bsch/WP-Filebase/commit/a87aa62d9e068c6d15ffdf36cbb81d069e4dc709

**Closed by f4bsch** 2015-12-08 22:42 UTC
